name: "Build"

on: pull_request

env:
  JAVA_OPTS: -Xms1g -Xmx3g

jobs:

  build:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    runs-on: '${{ matrix.os }}'

    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.6.0
        with:
          java-version: 8

      - name: Build and run test
        run: mvn compile test