name: "Build"

on: pull_request

env:
  JAVA_OPTS: -Xms1g -Xmx3g

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.3.1
        with:
          java-version: 8

        run: mvn compile test