name: "Build"

on: pull_request

env:
  JAVA_OPTS: -Xms1g -Xmx3g

jobs:

  build:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    runs-on: '${{ matrix.os }}'

    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action
        with:
          java-version: 8
          fetch-depth: 0

      - name: Restore Maven cache
        id: cache
        uses: actions/cache@v2.1.6
        with:
          path: |
            ${{ inputs.cache-path }}
            ${{ inputs.cache-path-add }}
          key: ${{ matrix.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ matrix.os }}-maven-

      - name: Build and run test
        run: mvn compile test